<template><div><h1 id="正则的扩展" tabindex="-1"><a class="header-anchor" href="#正则的扩展" aria-hidden="true">#</a> 正则的扩展</h1>
<h2 id="regexp-构造函数" tabindex="-1"><a class="header-anchor" href="#regexp-构造函数" aria-hidden="true">#</a> RegExp 构造函数</h2>
<p>在 ES5 中，<code v-pre>RegExp</code>构造函数的参数有两种情况。</p>
<p>第一种情况是，参数是字符串，这时第二个参数表示正则表达式的修饰符（flag）。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> regex <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token string">'xyz'</span><span class="token punctuation">,</span> <span class="token string">'i'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 等价于</span>
<span class="token keyword">var</span> regex <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">xyz</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><!-- more -->
<p>第二种情况是，参数是一个正则表示式，这时会返回一个原有正则表达式的拷贝。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> regex <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">xyz</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 等价于</span>
<span class="token keyword">var</span> regex <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">xyz</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>但是，ES5 不允许此时使用第二个参数添加修饰符，否则会报错。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> regex <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">xyz</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">,</span> <span class="token string">'i'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// Uncaught TypeError: Cannot supply flags when constructing one RegExp from another</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>ES6 改变了这种行为。如果<code v-pre>RegExp</code>构造函数第一个参数是一个正则对象，那么可以使用第二个参数指定修饰符。而且，返回的正则表达式会忽略原有的正则表达式的修饰符，只使用新指定的修饰符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">abc</span><span class="token regex-delimiter">/</span><span class="token regex-flags">ig</span></span><span class="token punctuation">,</span> <span class="token string">'i'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>flags
<span class="token comment">// "i"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，原有正则对象的修饰符是<code v-pre>ig</code>，它会被第二个参数<code v-pre>i</code>覆盖。</p>
<h2 id="字符串的正则方法" tabindex="-1"><a class="header-anchor" href="#字符串的正则方法" aria-hidden="true">#</a> 字符串的正则方法</h2>
<p>字符串对象共有 4 个方法，可以使用正则表达式：<code v-pre>match()</code>、<code v-pre>replace()</code>、<code v-pre>search()</code>和<code v-pre>split()</code>。</p>
<p>ES6 将这 4 个方法，在语言内部全部调用<code v-pre>RegExp</code>的实例方法，从而做到所有与正则相关的方法，全都定义在<code v-pre>RegExp</code>对象上。</p>
<ul>
<li><code v-pre>String.prototype.match</code> 调用 <code v-pre>RegExp.prototype[Symbol.match]</code></li>
<li><code v-pre>String.prototype.replace</code> 调用 <code v-pre>RegExp.prototype[Symbol.replace]</code></li>
<li><code v-pre>String.prototype.search</code> 调用 <code v-pre>RegExp.prototype[Symbol.search]</code></li>
<li><code v-pre>String.prototype.split</code> 调用 <code v-pre>RegExp.prototype[Symbol.split]</code></li>
</ul>
<h2 id="u-修饰符" tabindex="-1"><a class="header-anchor" href="#u-修饰符" aria-hidden="true">#</a> u 修饰符</h2>
<p>ES6 对正则表达式添加了<code v-pre>u</code>修饰符，含义为“Unicode 模式”，用来正确处理大于<code v-pre>\uFFFF</code>的 Unicode 字符。也就是说，会正确处理四个字节的 UTF-16 编码。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\uD83D</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'\uD83D\uDC2A'</span><span class="token punctuation">)</span> <span class="token comment">// false</span>
<span class="token operator">/</span><span class="token operator">^</span>\uD83D<span class="token operator">/</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'\uD83D\uDC2A'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，<code v-pre>\uD83D\uDC2A</code>是一个四个字节的 UTF-16 编码，代表一个字符。但是，ES5 不支持四个字节的 UTF-16 编码，会将其识别为两个字符，导致第二行代码结果为<code v-pre>true</code>。加了<code v-pre>u</code>修饰符以后，ES6 就会识别其为一个字符，所以第一行代码结果为<code v-pre>false</code>。</p>
<p>一旦加上<code v-pre>u</code>修饰符号，就会修改下面这些正则表达式的行为。</p>
<p><strong>（1）点字符</strong></p>
<p>点（<code v-pre>.</code>）字符在正则表达式中，含义是除了换行符以外的任意单个字符。对于码点大于<code v-pre>0xFFFF</code>的 Unicode 字符，点字符不能识别，必须加上<code v-pre>u</code>修饰符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> s <span class="token operator">=</span> <span class="token string">'𠮷'</span><span class="token punctuation">;</span>

<span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^.$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// false</span>
<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">.</span>$<span class="token operator">/</span>u<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码表示，如果不添加<code v-pre>u</code>修饰符，正则表达式就会认为字符串为两个字符，从而匹配失败。</p>
<p><strong>（2）Unicode 字符表示法</strong></p>
<p>ES6 新增了使用大括号表示 Unicode 字符，这种表示法在正则表达式中必须加上<code v-pre>u</code>修饰符，才能识别当中的大括号，否则会被解读为量词。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\u{61}</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'a'</span><span class="token punctuation">)</span> <span class="token comment">// false</span>
<span class="token operator">/</span>\u<span class="token punctuation">{</span><span class="token number">61</span><span class="token punctuation">}</span><span class="token operator">/</span>u<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'a'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
<span class="token operator">/</span>\u<span class="token punctuation">{</span>20BB7<span class="token punctuation">}</span><span class="token operator">/</span>u<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'𠮷'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码表示，如果不加<code v-pre>u</code>修饰符，正则表达式无法识别<code v-pre>\u{61}</code>这种表示法，只会认为这匹配 61 个连续的<code v-pre>u</code>。</p>
<p><strong>（3）量词</strong></p>
<p>使用<code v-pre>u</code>修饰符后，所有量词都会正确识别码点大于<code v-pre>0xFFFF</code>的 Unicode 字符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a{2}</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'aa'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
<span class="token operator">/</span>a<span class="token punctuation">{</span><span class="token number">2</span><span class="token punctuation">}</span><span class="token operator">/</span>u<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'aa'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
<span class="token operator">/</span>𠮷<span class="token punctuation">{</span><span class="token number">2</span><span class="token punctuation">}</span><span class="token operator">/</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'𠮷𠮷'</span><span class="token punctuation">)</span> <span class="token comment">// false</span>
<span class="token operator">/</span>𠮷<span class="token punctuation">{</span><span class="token number">2</span><span class="token punctuation">}</span><span class="token operator">/</span>u<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'𠮷𠮷'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>（4）预定义模式</strong></p>
<p><code v-pre>u</code>修饰符也影响到预定义模式，能否正确识别码点大于<code v-pre>0xFFFF</code>的 Unicode 字符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\S$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'𠮷'</span><span class="token punctuation">)</span> <span class="token comment">// false</span>
<span class="token operator">/</span><span class="token operator">^</span>\<span class="token constant">S</span>$<span class="token operator">/</span>u<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'𠮷'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码的<code v-pre>\S</code>是预定义模式，匹配所有非空白字符。只有加了<code v-pre>u</code>修饰符，它才能正确匹配码点大于<code v-pre>0xFFFF</code>的 Unicode 字符。</p>
<p>利用这一点，可以写出一个正确返回字符串长度的函数。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">codePointLength</span><span class="token punctuation">(</span><span class="token parameter">text</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">var</span> result <span class="token operator">=</span> text<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">[\s\S]</span><span class="token regex-delimiter">/</span><span class="token regex-flags">gu</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> result <span class="token operator">?</span> result<span class="token punctuation">.</span>length <span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token keyword">var</span> s <span class="token operator">=</span> <span class="token string">'𠮷𠮷'</span><span class="token punctuation">;</span>

s<span class="token punctuation">.</span>length <span class="token comment">// 4</span>
<span class="token function">codePointLength</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// 2</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>（5）i 修饰符</strong></p>
<p>有些 Unicode 字符的编码不同，但是字型很相近，比如，<code v-pre>\u004B</code>与<code v-pre>\u212A</code>都是大写的<code v-pre>K</code>。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">[a-z]</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'\u212A'</span><span class="token punctuation">)</span> <span class="token comment">// false</span>
<span class="token operator">/</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z<span class="token punctuation">]</span><span class="token operator">/</span>iu<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'\u212A'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，不加<code v-pre>u</code>修饰符，就无法识别非规范的<code v-pre>K</code>字符。</p>
<p><strong>（6）转义</strong></p>
<p>没有<code v-pre>u</code>修饰符的情况下，正则中没有定义的转义（如逗号的转义<code v-pre>\,</code>）无效，而在<code v-pre>u</code>模式会报错。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\,</span><span class="token regex-delimiter">/</span></span> <span class="token comment">// /\,/</span>
<span class="token operator">/</span>\<span class="token punctuation">,</span><span class="token operator">/</span>u <span class="token comment">// 报错</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，没有<code v-pre>u</code>修饰符时，逗号前面的反斜杠是无效的，加了<code v-pre>u</code>修饰符就报错。</p>
<h2 id="regexp-prototype-unicode-属性" tabindex="-1"><a class="header-anchor" href="#regexp-prototype-unicode-属性" aria-hidden="true">#</a> RegExp.prototype.unicode 属性</h2>
<p>正则实例对象新增<code v-pre>unicode</code>属性，表示是否设置了<code v-pre>u</code>修饰符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> r1 <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">hello</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
<span class="token keyword">const</span> r2 <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">hello</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">;</span>

r1<span class="token punctuation">.</span>unicode <span class="token comment">// false</span>
r2<span class="token punctuation">.</span>unicode <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，正则表达式是否设置了<code v-pre>u</code>修饰符，可以从<code v-pre>unicode</code>属性看出来。</p>
<h2 id="y-修饰符" tabindex="-1"><a class="header-anchor" href="#y-修饰符" aria-hidden="true">#</a> y 修饰符</h2>
<p>除了<code v-pre>u</code>修饰符，ES6 还为正则表达式添加了<code v-pre>y</code>修饰符，叫做“粘连”（sticky）修饰符。</p>
<p><code v-pre>y</code>修饰符的作用与<code v-pre>g</code>修饰符类似，也是全局匹配，后一次匹配都从上一次匹配成功的下一个位置开始。不同之处在于，<code v-pre>g</code>修饰符只要剩余位置中存在匹配就可，而<code v-pre>y</code>修饰符确保匹配必须从剩余的第一个位置开始，这也就是“粘连”的涵义。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> s <span class="token operator">=</span> <span class="token string">'aaa_aa_a'</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> r1 <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a+</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
<span class="token keyword">var</span> r2 <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a+</span><span class="token regex-delimiter">/</span><span class="token regex-flags">y</span></span><span class="token punctuation">;</span>

r1<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// ["aaa"]</span>
r2<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// ["aaa"]</span>

r1<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// ["aa"]</span>
r2<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// null</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码有两个正则表达式，一个使用<code v-pre>g</code>修饰符，另一个使用<code v-pre>y</code>修饰符。这两个正则表达式各执行了两次，第一次执行的时候，两者行为相同，剩余字符串都是<code v-pre>_aa_a</code>。由于<code v-pre>g</code>修饰没有位置要求，所以第二次执行会返回结果，而<code v-pre>y</code>修饰符要求匹配必须从头部开始，所以返回<code v-pre>null</code>。</p>
<p>如果改一下正则表达式，保证每次都能头部匹配，<code v-pre>y</code>修饰符就会返回结果了。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> s <span class="token operator">=</span> <span class="token string">'aaa_aa_a'</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> r <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a+_</span><span class="token regex-delimiter">/</span><span class="token regex-flags">y</span></span><span class="token punctuation">;</span>

r<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// ["aaa_"]</span>
r<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// ["aa_"]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码每次匹配，都是从剩余字符串的头部开始。</p>
<p>使用<code v-pre>lastIndex</code>属性，可以更好地说明<code v-pre>y</code>修饰符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">REGEX</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>

<span class="token comment">// 指定从2号位置（y）开始匹配</span>
<span class="token constant">REGEX</span><span class="token punctuation">.</span>lastIndex <span class="token operator">=</span> <span class="token number">2</span><span class="token punctuation">;</span>

<span class="token comment">// 匹配成功</span>
<span class="token keyword">const</span> match <span class="token operator">=</span> <span class="token constant">REGEX</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'xaya'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// 在3号位置匹配成功</span>
match<span class="token punctuation">.</span>index <span class="token comment">// 3</span>

<span class="token comment">// 下一次匹配从4号位开始</span>
<span class="token constant">REGEX</span><span class="token punctuation">.</span>lastIndex <span class="token comment">// 4</span>

<span class="token comment">// 4号位开始匹配失败</span>
<span class="token constant">REGEX</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'xaya'</span><span class="token punctuation">)</span> <span class="token comment">// null</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，<code v-pre>lastIndex</code>属性指定每次搜索的开始位置，<code v-pre>g</code>修饰符从这个位置开始向后搜索，直到发现匹配为止。</p>
<p><code v-pre>y</code>修饰符同样遵守<code v-pre>lastIndex</code>属性，但是要求必须在<code v-pre>lastIndex</code>指定的位置发现匹配。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">REGEX</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a</span><span class="token regex-delimiter">/</span><span class="token regex-flags">y</span></span><span class="token punctuation">;</span>

<span class="token comment">// 指定从2号位置开始匹配</span>
<span class="token constant">REGEX</span><span class="token punctuation">.</span>lastIndex <span class="token operator">=</span> <span class="token number">2</span><span class="token punctuation">;</span>

<span class="token comment">// 不是粘连，匹配失败</span>
<span class="token constant">REGEX</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'xaya'</span><span class="token punctuation">)</span> <span class="token comment">// null</span>

<span class="token comment">// 指定从3号位置开始匹配</span>
<span class="token constant">REGEX</span><span class="token punctuation">.</span>lastIndex <span class="token operator">=</span> <span class="token number">3</span><span class="token punctuation">;</span>

<span class="token comment">// 3号位置是粘连，匹配成功</span>
<span class="token keyword">const</span> match <span class="token operator">=</span> <span class="token constant">REGEX</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'xaya'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
match<span class="token punctuation">.</span>index <span class="token comment">// 3</span>
<span class="token constant">REGEX</span><span class="token punctuation">.</span>lastIndex <span class="token comment">// 4</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>实际上，<code v-pre>y</code>修饰符号隐含了头部匹配的标志<code v-pre>^</code>。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">b</span><span class="token regex-delimiter">/</span><span class="token regex-flags">y</span></span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'aba'</span><span class="token punctuation">)</span>
<span class="token comment">// null</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码由于不能保证头部匹配，所以返回<code v-pre>null</code>。<code v-pre>y</code>修饰符的设计本意，就是让头部匹配的标志<code v-pre>^</code>在全局匹配中都有效。</p>
<p>下面是字符串对象的<code v-pre>replace</code>方法的例子。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">REGEX</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a</span><span class="token regex-delimiter">/</span><span class="token regex-flags">gy</span></span><span class="token punctuation">;</span>
<span class="token string">'aaxa'</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token constant">REGEX</span><span class="token punctuation">,</span> <span class="token string">'-'</span><span class="token punctuation">)</span> <span class="token comment">// '--xa'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，最后一个<code v-pre>a</code>因为不是出现在下一次匹配的头部，所以不会被替换。</p>
<p>单单一个<code v-pre>y</code>修饰符对<code v-pre>match</code>方法，只能返回第一个匹配，必须与<code v-pre>g</code>修饰符联用，才能返回所有匹配。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token string">'a1a2a3'</span><span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a\d</span><span class="token regex-delimiter">/</span><span class="token regex-flags">y</span></span><span class="token punctuation">)</span> <span class="token comment">// ["a1"]</span>
<span class="token string">'a1a2a3'</span><span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a\d</span><span class="token regex-delimiter">/</span><span class="token regex-flags">gy</span></span><span class="token punctuation">)</span> <span class="token comment">// ["a1", "a2", "a3"]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>y</code>修饰符的一个应用，是从字符串提取 token（词元），<code v-pre>y</code>修饰符确保了匹配之间不会有漏掉的字符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">TOKEN_Y</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\s*(\+|[0-9]+)\s*</span><span class="token regex-delimiter">/</span><span class="token regex-flags">y</span></span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token constant">TOKEN_G</span>  <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\s*(\+|[0-9]+)\s*</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>

<span class="token function">tokenize</span><span class="token punctuation">(</span><span class="token constant">TOKEN_Y</span><span class="token punctuation">,</span> <span class="token string">'3 + 4'</span><span class="token punctuation">)</span>
<span class="token comment">// [ '3', '+', '4' ]</span>
<span class="token function">tokenize</span><span class="token punctuation">(</span><span class="token constant">TOKEN_G</span><span class="token punctuation">,</span> <span class="token string">'3 + 4'</span><span class="token punctuation">)</span>
<span class="token comment">// [ '3', '+', '4' ]</span>

<span class="token keyword">function</span> <span class="token function">tokenize</span><span class="token punctuation">(</span><span class="token parameter"><span class="token constant">TOKEN_REGEX</span><span class="token punctuation">,</span> str</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> result <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">let</span> match<span class="token punctuation">;</span>
  <span class="token keyword">while</span> <span class="token punctuation">(</span>match <span class="token operator">=</span> <span class="token constant">TOKEN_REGEX</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    result<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>match<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token keyword">return</span> result<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，如果字符串里面没有非法字符，<code v-pre>y</code>修饰符与<code v-pre>g</code>修饰符的提取结果是一样的。但是，一旦出现非法字符，两者的行为就不一样了。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token function">tokenize</span><span class="token punctuation">(</span><span class="token constant">TOKEN_Y</span><span class="token punctuation">,</span> <span class="token string">'3x + 4'</span><span class="token punctuation">)</span>
<span class="token comment">// [ '3' ]</span>
<span class="token function">tokenize</span><span class="token punctuation">(</span><span class="token constant">TOKEN_G</span><span class="token punctuation">,</span> <span class="token string">'3x + 4'</span><span class="token punctuation">)</span>
<span class="token comment">// [ '3', '+', '4' ]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，<code v-pre>g</code>修饰符会忽略非法字符，而<code v-pre>y</code>修饰符不会，这样就很容易发现错误。</p>
<h2 id="regexp-prototype-sticky-属性" tabindex="-1"><a class="header-anchor" href="#regexp-prototype-sticky-属性" aria-hidden="true">#</a> RegExp.prototype.sticky 属性</h2>
<p>与<code v-pre>y</code>修饰符相匹配，ES6 的正则实例对象多了<code v-pre>sticky</code>属性，表示是否设置了<code v-pre>y</code>修饰符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> r <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">hello\d</span><span class="token regex-delimiter">/</span><span class="token regex-flags">y</span></span><span class="token punctuation">;</span>
r<span class="token punctuation">.</span>sticky <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="regexp-prototype-flags-属性" tabindex="-1"><a class="header-anchor" href="#regexp-prototype-flags-属性" aria-hidden="true">#</a> RegExp.prototype.flags 属性</h2>
<p>ES6 为正则表达式新增了<code v-pre>flags</code>属性，会返回正则表达式的修饰符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// ES5 的 source 属性</span>
<span class="token comment">// 返回正则表达式的正文</span>
<span class="token operator">/</span>abc<span class="token operator">/</span>ig<span class="token punctuation">.</span>source
<span class="token comment">// "abc"</span>

<span class="token comment">// ES6 的 flags 属性</span>
<span class="token comment">// 返回正则表达式的修饰符</span>
<span class="token operator">/</span>abc<span class="token operator">/</span>ig<span class="token punctuation">.</span>flags
<span class="token comment">// 'gi'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="s-修饰符-dotall-模式" tabindex="-1"><a class="header-anchor" href="#s-修饰符-dotall-模式" aria-hidden="true">#</a> s 修饰符：dotAll 模式</h2>
<p>正则表达式中，点（<code v-pre>.</code>）是一个特殊字符，代表任意的单个字符，但是有两个例外。一个是四个字节的 UTF-16 字符，这个可以用<code v-pre>u</code>修饰符解决；另一个是行终止符（line terminator character）。</p>
<p>所谓行终止符，就是该字符表示一行的终结。以下四个字符属于“行终止符”。</p>
<ul>
<li>U+000A 换行符（<code v-pre>\n</code>）</li>
<li>U+000D 回车符（<code v-pre>\r</code>）</li>
<li>U+2028 行分隔符（line separator）</li>
<li>U+2029 段分隔符（paragraph separator）</li>
</ul>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">foo.bar</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'foo\nbar'</span><span class="token punctuation">)</span>
<span class="token comment">// false</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，因为<code v-pre>.</code>不匹配<code v-pre>\n</code>，所以正则表达式返回<code v-pre>false</code>。</p>
<p>但是，很多时候我们希望匹配的是任意单个字符，这时有一种变通的写法。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">foo[^]bar</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'foo\nbar'</span><span class="token punctuation">)</span>
<span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>这种解决方案毕竟不太符合直觉，ES2018 <a href="https://github.com/tc39/proposal-regexp-dotall-flag" target="_blank" rel="noopener noreferrer">引入<ExternalLinkIcon/></a><code v-pre>s</code>修饰符，使得<code v-pre>.</code>可以匹配任意单个字符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">foo.bar</span><span class="token regex-delimiter">/</span><span class="token regex-flags">s</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'foo\nbar'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>这被称为<code v-pre>dotAll</code>模式，即点（dot）代表一切字符。所以，正则表达式还引入了一个<code v-pre>dotAll</code>属性，返回一个布尔值，表示该正则表达式是否处在<code v-pre>dotAll</code>模式。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> re <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">foo.bar</span><span class="token regex-delimiter">/</span><span class="token regex-flags">s</span></span><span class="token punctuation">;</span>
<span class="token comment">// 另一种写法</span>
<span class="token comment">// const re = new RegExp('foo.bar', 's');</span>

re<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'foo\nbar'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
re<span class="token punctuation">.</span>dotAll <span class="token comment">// true</span>
re<span class="token punctuation">.</span>flags <span class="token comment">// 's'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>/s</code>修饰符和多行修饰符<code v-pre>/m</code>不冲突，两者一起使用的情况下，<code v-pre>.</code>匹配所有字符，而<code v-pre>^</code>和<code v-pre>$</code>匹配每一行的行首和行尾。</p>
<h2 id="后行断言" tabindex="-1"><a class="header-anchor" href="#后行断言" aria-hidden="true">#</a> 后行断言</h2>
<p>JavaScript 语言的正则表达式，只支持先行断言（lookahead）和先行否定断言（negative lookahead），不支持后行断言（lookbehind）和后行否定断言（negative lookbehind）。ES2018 引入<a href="https://github.com/tc39/proposal-regexp-lookbehind" target="_blank" rel="noopener noreferrer">后行断言<ExternalLinkIcon/></a>，V8 引擎 4.9 版（Chrome 62）已经支持。</p>
<p>“先行断言”指的是，<code v-pre>x</code>只有在<code v-pre>y</code>前面才匹配，必须写成<code v-pre>/x(?=y)/</code>。比如，只匹配百分号之前的数字，要写成<code v-pre>/\d+(?=%)/</code>。“先行否定断言”指的是，<code v-pre>x</code>只有不在<code v-pre>y</code>前面才匹配，必须写成<code v-pre>/x(?!y)/</code>。比如，只匹配不在百分号之前的数字，要写成<code v-pre>/\d+(?!%)/</code>。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\d+(?=%)</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'100% of US presidents have been male'</span><span class="token punctuation">)</span>  <span class="token comment">// ["100"]</span>
<span class="token operator">/</span>\d<span class="token operator">+</span><span class="token punctuation">(</span><span class="token operator">?</span><span class="token operator">!</span><span class="token operator">%</span><span class="token punctuation">)</span><span class="token operator">/</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'that’s all 44 of them'</span><span class="token punctuation">)</span>                 <span class="token comment">// ["44"]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面两个字符串，如果互换正则表达式，就不会得到相同结果。另外，还可以看到，“先行断言”括号之中的部分（<code v-pre>(?=%)</code>），是不计入返回结果的。</p>
<p>“后行断言”正好与“先行断言”相反，<code v-pre>x</code>只有在<code v-pre>y</code>后面才匹配，必须写成<code v-pre>/(?&lt;=y)x/</code>。比如，只匹配美元符号之后的数字，要写成<code v-pre>/(?&lt;=\$)\d+/</code>。“后行否定断言”则与“先行否定断言”相反，<code v-pre>x</code>只有不在<code v-pre>y</code>后面才匹配，必须写成<code v-pre>/(?&lt;!y)x/</code>。比如，只匹配不在美元符号后面的数字，要写成<code v-pre>/(?&lt;!\$)\d+/</code>。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(?&lt;=\$)\d+</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'Benjamin Franklin is on the $100 bill'</span><span class="token punctuation">)</span>  <span class="token comment">// ["100"]</span>
<span class="token operator">/</span><span class="token punctuation">(</span><span class="token operator">?</span><span class="token operator">&lt;</span><span class="token operator">!</span>\$<span class="token punctuation">)</span>\d<span class="token operator">+</span><span class="token operator">/</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'it’s is worth about €90'</span><span class="token punctuation">)</span>                <span class="token comment">// ["90"]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面的例子中，“后行断言”的括号之中的部分（<code v-pre>(?&lt;=\$)</code>），也是不计入返回结果。</p>
<p>下面的例子是使用后行断言进行字符串替换。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">RE_DOLLAR_PREFIX</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(?&lt;=\$)foo</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
<span class="token string">'$foo %foo foo'</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token constant">RE_DOLLAR_PREFIX</span><span class="token punctuation">,</span> <span class="token string">'bar'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// '$bar %foo foo'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，只有在美元符号后面的<code v-pre>foo</code>才会被替换。</p>
<p>“后行断言”的实现，需要先匹配<code v-pre>/(?&lt;=y)x/</code>的<code v-pre>x</code>，然后再回到左边，匹配<code v-pre>y</code>的部分。这种“先右后左”的执行顺序，与所有其他正则操作相反，导致了一些不符合预期的行为。</p>
<p>首先，后行断言的组匹配，与正常情况下结果是不一样的。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(?&lt;=(\d+)(\d+))$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'1053'</span><span class="token punctuation">)</span> <span class="token comment">// ["", "1", "053"]</span>
<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">(</span>\d<span class="token operator">+</span><span class="token punctuation">)</span><span class="token punctuation">(</span>\d<span class="token operator">+</span><span class="token punctuation">)</span>$<span class="token operator">/</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'1053'</span><span class="token punctuation">)</span> <span class="token comment">// ["1053", "105", "3"]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，需要捕捉两个组匹配。没有“后行断言”时，第一个括号是贪婪模式，第二个括号只能捕获一个字符，所以结果是<code v-pre>105</code>和<code v-pre>3</code>。而“后行断言”时，由于执行顺序是从右到左，第二个括号是贪婪模式，第一个括号只能捕获一个字符，所以结果是<code v-pre>1</code>和<code v-pre>053</code>。</p>
<p>其次，“后行断言”的反斜杠引用，也与通常的顺序相反，必须放在对应的那个括号之前。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(?&lt;=(o)d\1)r</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'hodor'</span><span class="token punctuation">)</span>  <span class="token comment">// null</span>
<span class="token operator">/</span><span class="token punctuation">(</span><span class="token operator">?</span><span class="token operator">&lt;=</span>\<span class="token number">1</span><span class="token function">d</span><span class="token punctuation">(</span>o<span class="token punctuation">)</span><span class="token punctuation">)</span>r<span class="token operator">/</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'hodor'</span><span class="token punctuation">)</span>  <span class="token comment">// ["r", "o"]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，如果后行断言的反斜杠引用（<code v-pre>\1</code>）放在括号的后面，就不会得到匹配结果，必须放在前面才可以。因为后行断言是先从左到右扫描，发现匹配以后再回过头，从右到左完成反斜杠引用。</p>
<h2 id="unicode-属性类" tabindex="-1"><a class="header-anchor" href="#unicode-属性类" aria-hidden="true">#</a> Unicode 属性类</h2>
<p>ES2018 <a href="https://github.com/tc39/proposal-regexp-unicode-property-escapes" target="_blank" rel="noopener noreferrer">引入<ExternalLinkIcon/></a>了一种新的类的写法<code v-pre>\p{...}</code>和<code v-pre>\P{...}</code>，允许正则表达式匹配符合 Unicode 某种属性的所有字符。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> regexGreekSymbol <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\p{Script=Greek}</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">;</span>
regexGreekSymbol<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'π'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，<code v-pre>\p{Script=Greek}</code>指定匹配一个希腊文字母，所以匹配<code v-pre>π</code>成功。</p>
<p>Unicode 属性类要指定属性名和属性值。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>\p<span class="token punctuation">{</span>UnicodePropertyName<span class="token operator">=</span>UnicodePropertyValue<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>对于某些属性，可以只写属性名，或者只写属性值。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>\p<span class="token punctuation">{</span>UnicodePropertyName<span class="token punctuation">}</span>
\p<span class="token punctuation">{</span>UnicodePropertyValue<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>\P{…}</code>是<code v-pre>\p{…}</code>的反向匹配，即匹配不满足条件的字符。</p>
<p>注意，这两种类只对 Unicode 有效，所以使用的时候一定要加上<code v-pre>u</code>修饰符。如果不加<code v-pre>u</code>修饰符，正则表达式使用<code v-pre>\p</code>和<code v-pre>\P</code>会报错，ECMAScript 预留了这两个类。</p>
<p>由于 Unicode 的各种属性非常多，所以这种新的类的表达能力非常强。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> regex <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\p{Decimal_Number}+$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">;</span>
regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'𝟏𝟐𝟑𝟜𝟝𝟞𝟩𝟪𝟫𝟬𝟭𝟮𝟯𝟺𝟻𝟼'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，属性类指定匹配所有十进制字符，可以看到各种字型的十进制字符都会匹配成功。</p>
<p><code v-pre>\p{Number}</code>甚至能匹配罗马数字。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 匹配所有数字</span>
<span class="token keyword">const</span> regex <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\p{Number}+$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">;</span>
regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'²³¹¼½¾'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'㉛㉜㉝'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫ'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>下面是其他一些例子。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 匹配所有空格</span>
\p<span class="token punctuation">{</span>White_Space<span class="token punctuation">}</span>

<span class="token comment">// 匹配各种文字的所有字母，等同于 Unicode 版的 \w</span>
<span class="token punctuation">[</span>\p<span class="token punctuation">{</span>Alphabetic<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Mark<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Decimal_Number<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Connector_Punctuation<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Join_Control<span class="token punctuation">}</span><span class="token punctuation">]</span>

<span class="token comment">// 匹配各种文字的所有非字母的字符，等同于 Unicode 版的 \W</span>
<span class="token punctuation">[</span><span class="token operator">^</span>\p<span class="token punctuation">{</span>Alphabetic<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Mark<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Decimal_Number<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Connector_Punctuation<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Join_Control<span class="token punctuation">}</span><span class="token punctuation">]</span>

<span class="token comment">// 匹配 Emoji</span>
<span class="token operator">/</span>\p<span class="token punctuation">{</span>Emoji_Modifier_Base<span class="token punctuation">}</span>\p<span class="token punctuation">{</span>Emoji_Modifier<span class="token punctuation">}</span><span class="token operator">?</span><span class="token operator">|</span>\p<span class="token punctuation">{</span>Emoji_Presentation<span class="token punctuation">}</span><span class="token operator">|</span>\p<span class="token punctuation">{</span>Emoji<span class="token punctuation">}</span>\uFE0F<span class="token operator">/</span>gu

<span class="token comment">// 匹配所有的箭头字符</span>
<span class="token keyword">const</span> regexArrows <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\p{Block=Arrows}+$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">;</span>
regexArrows<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'←↑→↓↔↕↖↗↘↙⇏⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙⇧⇩'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="具名组匹配" tabindex="-1"><a class="header-anchor" href="#具名组匹配" aria-hidden="true">#</a> 具名组匹配</h2>
<h3 id="简介" tabindex="-1"><a class="header-anchor" href="#简介" aria-hidden="true">#</a> 简介</h3>
<p>正则表达式使用圆括号进行组匹配。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">RE_DATE</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(\d{4})-(\d{2})-(\d{2})</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>上面代码中，正则表达式里面有三组圆括号。使用<code v-pre>exec</code>方法，就可以将这三组匹配结果提取出来。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">RE_DATE</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(\d{4})-(\d{2})-(\d{2})</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>

<span class="token keyword">const</span> matchObj <span class="token operator">=</span> <span class="token constant">RE_DATE</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'1999-12-31'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> year <span class="token operator">=</span> matchObj<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">// 1999</span>
<span class="token keyword">const</span> month <span class="token operator">=</span> matchObj<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">// 12</span>
<span class="token keyword">const</span> day <span class="token operator">=</span> matchObj<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">// 31</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>组匹配的一个问题是，每一组的匹配含义不容易看出来，而且只能用数字序号（比如<code v-pre>matchObj[1]</code>）引用，要是组的顺序变了，引用的时候就必须修改序号。</p>
<p>ES2018 引入了<a href="https://github.com/tc39/proposal-regexp-named-groups" target="_blank" rel="noopener noreferrer">具名组匹配<ExternalLinkIcon/></a>（Named Capture Groups），允许为每一个组匹配指定一个名字，既便于阅读代码，又便于引用。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">RE_DATE</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(?&lt;year>\d{4})-(?&lt;month>\d{2})-(?&lt;day>\d{2})</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>

<span class="token keyword">const</span> matchObj <span class="token operator">=</span> <span class="token constant">RE_DATE</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'1999-12-31'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> year <span class="token operator">=</span> matchObj<span class="token punctuation">.</span>groups<span class="token punctuation">.</span>year<span class="token punctuation">;</span> <span class="token comment">// 1999</span>
<span class="token keyword">const</span> month <span class="token operator">=</span> matchObj<span class="token punctuation">.</span>groups<span class="token punctuation">.</span>month<span class="token punctuation">;</span> <span class="token comment">// 12</span>
<span class="token keyword">const</span> day <span class="token operator">=</span> matchObj<span class="token punctuation">.</span>groups<span class="token punctuation">.</span>day<span class="token punctuation">;</span> <span class="token comment">// 31</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，“具名组匹配”在圆括号内部，模式的头部添加“问号 + 尖括号 + 组名”（<code v-pre>?&lt;year&gt;</code>），然后就可以在<code v-pre>exec</code>方法返回结果的<code v-pre>groups</code>属性上引用该组名。同时，数字序号（<code v-pre>matchObj[1]</code>）依然有效。</p>
<p>具名组匹配等于为每一组匹配加上了 ID，便于描述匹配的目的。如果组的顺序变了，也不用改变匹配后的处理代码。</p>
<p>如果具名组没有匹配，那么对应的<code v-pre>groups</code>对象属性会是<code v-pre>undefined</code>。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">RE_OPT_A</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^(?&lt;as>a+)?$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
<span class="token keyword">const</span> matchObj <span class="token operator">=</span> <span class="token constant">RE_OPT_A</span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

matchObj<span class="token punctuation">.</span>groups<span class="token punctuation">.</span>as <span class="token comment">// undefined</span>
<span class="token string">'as'</span> <span class="token keyword">in</span> matchObj<span class="token punctuation">.</span>groups <span class="token comment">// true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，具名组<code v-pre>as</code>没有找到匹配，那么<code v-pre>matchObj.groups.as</code>属性值就是<code v-pre>undefined</code>，并且<code v-pre>as</code>这个键名在<code v-pre>groups</code>是始终存在的。</p>
<h3 id="解构赋值和替换" tabindex="-1"><a class="header-anchor" href="#解构赋值和替换" aria-hidden="true">#</a> 解构赋值和替换</h3>
<p>有了具名组匹配以后，可以使用解构赋值直接从匹配结果上为变量赋值。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> <span class="token punctuation">{</span><span class="token literal-property property">groups</span><span class="token operator">:</span> <span class="token punctuation">{</span>one<span class="token punctuation">,</span> two<span class="token punctuation">}</span><span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^(?&lt;one>.*):(?&lt;two>.*)$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span><span class="token string">'foo:bar'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
one  <span class="token comment">// foo</span>
two  <span class="token comment">// bar</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>字符串替换时，使用<code v-pre>$&lt;组名&gt;</code>引用具名组。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> re <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(?&lt;year>\d{4})-(?&lt;month>\d{2})-(?&lt;day>\d{2})</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">;</span>

<span class="token string">'2015-01-02'</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>re<span class="token punctuation">,</span> <span class="token string">'$&lt;day>/$&lt;month>/$&lt;year>'</span><span class="token punctuation">)</span>
<span class="token comment">// '02/01/2015'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，<code v-pre>replace</code>方法的第二个参数是一个字符串，而不是正则表达式。</p>
<p><code v-pre>replace</code>方法的第二个参数也可以是函数，该函数的参数序列如下。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token string">'2015-01-02'</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>re<span class="token punctuation">,</span> <span class="token punctuation">(</span>
   matched<span class="token punctuation">,</span> <span class="token comment">// 整个匹配结果 2015-01-02</span>
   capture1<span class="token punctuation">,</span> <span class="token comment">// 第一个组匹配 2015</span>
   capture2<span class="token punctuation">,</span> <span class="token comment">// 第二个组匹配 01</span>
   capture3<span class="token punctuation">,</span> <span class="token comment">// 第三个组匹配 02</span>
   position<span class="token punctuation">,</span> <span class="token comment">// 匹配开始的位置 0</span>
   <span class="token constant">S</span><span class="token punctuation">,</span> <span class="token comment">// 原字符串 2015-01-02</span>
   groups <span class="token comment">// 具名组构成的一个对象 {year, month, day}</span>
 <span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
 <span class="token keyword">let</span> <span class="token punctuation">{</span>day<span class="token punctuation">,</span> month<span class="token punctuation">,</span> year<span class="token punctuation">}</span> <span class="token operator">=</span> groups<span class="token punctuation">;</span>
 <span class="token keyword">return</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>day<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>month<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>year<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>具名组匹配在原来的基础上，新增了最后一个函数参数：具名组构成的一个对象。函数内部可以直接对这个对象进行解构赋值。</p>
<h3 id="引用" tabindex="-1"><a class="header-anchor" href="#引用" aria-hidden="true">#</a> 引用</h3>
<p>如果要在正则表达式内部引用某个“具名组匹配”，可以使用<code v-pre>\k&lt;组名&gt;</code>的写法。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">RE_TWICE</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^(?&lt;word>[a-z]+)!\k&lt;word>$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
<span class="token constant">RE_TWICE</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'abc!abc'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
<span class="token constant">RE_TWICE</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'abc!ab'</span><span class="token punctuation">)</span> <span class="token comment">// false</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>数字引用（<code v-pre>\1</code>）依然有效。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">RE_TWICE</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^(?&lt;word>[a-z]+)!\1$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
<span class="token constant">RE_TWICE</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'abc!abc'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
<span class="token constant">RE_TWICE</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'abc!ab'</span><span class="token punctuation">)</span> <span class="token comment">// false</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这两种引用语法还可以同时使用。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token constant">RE_TWICE</span> <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^(?&lt;word>[a-z]+)!\k&lt;word>!\1$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
<span class="token constant">RE_TWICE</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'abc!abc!abc'</span><span class="token punctuation">)</span> <span class="token comment">// true</span>
<span class="token constant">RE_TWICE</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token string">'abc!abc!ab'</span><span class="token punctuation">)</span> <span class="token comment">// false</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="string-prototype-matchall" tabindex="-1"><a class="header-anchor" href="#string-prototype-matchall" aria-hidden="true">#</a> String.prototype.matchAll()</h2>
<p>如果一个正则表达式在字符串里面有多个匹配，现在一般使用<code v-pre>g</code>修饰符或<code v-pre>y</code>修饰符，在循环里面逐一取出。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> regex <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">t(e)(st(\d?))</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
<span class="token keyword">var</span> string <span class="token operator">=</span> <span class="token string">'test1test2test3'</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> matches <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> match<span class="token punctuation">;</span>
<span class="token keyword">while</span> <span class="token punctuation">(</span>match <span class="token operator">=</span> regex<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>string<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  matches<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>match<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

matches
<span class="token comment">// [</span>
<span class="token comment">//   ["test1", "e", "st1", "1", index: 0, input: "test1test2test3"],</span>
<span class="token comment">//   ["test2", "e", "st2", "2", index: 5, input: "test1test2test3"],</span>
<span class="token comment">//   ["test3", "e", "st3", "3", index: 10, input: "test1test2test3"]</span>
<span class="token comment">// ]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，<code v-pre>while</code>循环取出每一轮的正则匹配，一共三轮。</p>
<p><a href="https://github.com/tc39/proposal-string-matchall" target="_blank" rel="noopener noreferrer">ES2020<ExternalLinkIcon/></a> 增加了<code v-pre>String.prototype.matchAll()</code>方法，可以一次性取出所有匹配。不过，它返回的是一个遍历器（Iterator），而不是数组。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> string <span class="token operator">=</span> <span class="token string">'test1test2test3'</span><span class="token punctuation">;</span>

<span class="token comment">// g 修饰符加不加都可以</span>
<span class="token keyword">const</span> regex <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">t(e)(st(\d?))</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>

<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">const</span> match <span class="token keyword">of</span> string<span class="token punctuation">.</span><span class="token function">matchAll</span><span class="token punctuation">(</span>regex<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>match<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">// ["test1", "e", "st1", "1", index: 0, input: "test1test2test3"]</span>
<span class="token comment">// ["test2", "e", "st2", "2", index: 5, input: "test1test2test3"]</span>
<span class="token comment">// ["test3", "e", "st3", "3", index: 10, input: "test1test2test3"]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面代码中，由于<code v-pre>string.matchAll(regex)</code>返回的是遍历器，所以可以用<code v-pre>for...of</code>循环取出。相对于返回数组，返回遍历器的好处在于，如果匹配结果是一个很大的数组，那么遍历器比较节省资源。</p>
<p>遍历器转为数组是非常简单的，使用<code v-pre>...</code>运算符和<code v-pre>Array.from()</code>方法就可以了。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 转为数组方法一</span>
<span class="token punctuation">[</span><span class="token operator">...</span>string<span class="token punctuation">.</span><span class="token function">matchAll</span><span class="token punctuation">(</span>regex<span class="token punctuation">)</span><span class="token punctuation">]</span>

<span class="token comment">// 转为数组方法二</span>
Array<span class="token punctuation">.</span><span class="token function">from</span><span class="token punctuation">(</span>string<span class="token punctuation">.</span><span class="token function">matchAll</span><span class="token punctuation">(</span>regex<span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


