<template><div><h1 id="路由懒加载" tabindex="-1"><a class="header-anchor" href="#路由懒加载" aria-hidden="true">#</a> 路由懒加载</h1>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 路由同步加载</span>
<span class="token comment">// import Recommend from '@/components/recommend/recommend'</span>
<span class="token comment">// import Singer from '@/components/singer/singer'</span>
<span class="token comment">// import Rank from '@/components/rank/rank'</span>
<span class="token comment">// import Search from '@/components/search/search'</span>
<span class="token comment">// import SingerDetail from '@/components/singer-detail/singer-detail'</span>
<span class="token comment">// import Disc from '@/components/disc/disc'</span>
<span class="token comment">// import TopList from '@/components/top-list/top-list'</span>
<span class="token comment">// import UserCenter from '@/components/user-center/user-center'</span>

Vue<span class="token punctuation">.</span><span class="token function">use</span><span class="token punctuation">(</span>Router<span class="token punctuation">)</span>

<span class="token comment">// 路由懒加载</span>
<span class="token keyword">const</span> <span class="token function-variable function">Recommend</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token string">'@/components/recommend/recommend'</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> <span class="token function-variable function">Singer</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token string">'@/components/singer/singer'</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> <span class="token function-variable function">Rank</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token string">'@/components/rank/rank'</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> <span class="token function-variable function">Search</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token string">'@/components/search/search'</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> <span class="token function-variable function">SingerDetail</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token string">'@/components/singer-detail/singer-detail'</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> <span class="token function-variable function">Disc</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token string">'@/components/disc/disc'</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> <span class="token function-variable function">TopList</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token string">'@/components/top-list/top-list'</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> <span class="token function-variable function">UserCenter</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token string">'@/components/user-center/user-center'</span><span class="token punctuation">)</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使用路由懒加载可使app.js文件变小，进入不同路由在分别加载该路由的js。</p>
</div></template>


