name: build-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependent Node Pkgs
      run: npm install
    
    - name: Deploy # 部署
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # 部署后提交到那个分支
        folder: docs/.vuepress/dist # 这里填打包好的目录名称
