# on: 触发workflow的条件，通常是某些事件，例如：release、push、pull_request等。
on:
  push:
    branches:
      - main

# workflow的名称。如果省略该字段，默认为当前workflow的文件名。
name: Release

jobs:
  release-please:
    # 运行所需要的虚拟机环境,它是必填字段
    runs-on: ubuntu-latest
    # steps指定每个任务的运行步骤，可以包含一个或多个步骤。
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: .github/workflows/release-please-config.json
          manifest-file: .github/workflows/release-please-manifest.json
          release-type: node