# on: 触发workflow的条件，通常是某些事件，例如：release、push、pull_request等。
on:
  workflow_run: 
    workflows: ["auto-merge"] #自动合并后触发
    types:
      - completed

  push:
    branches:
      - main

# workflow的名称。如果省略该字段，默认为当前workflow的文件名。
name: release

jobs:
  release-please:
    # 运行所需要的虚拟机环境,它是必填字段
    runs-on: ubuntu-latest
    # steps指定每个任务的运行步骤，可以包含一个或多个步骤。
    steps:
      # config git to github-actions[bot]
      - name: config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/workflows/release-please-config.json
          manifest-file: .github/workflows/release-please-manifest.json
          release-type: node
      # 直接合并
      - name: Auto Merge
        uses: 'pascalgn/automerge-action@v0.15.6'
        continue-on-error: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
          # merge if create by github-actions[bot]
          MARGE_FILTER_CREATOR: 'github-actions[bot]'
          # MERGE_FILTER_BRANCH: 'main'
          MERGE_METHOD: 'squash'
